# messy...

$(bits)main.o: main.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)tests.o: tests.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)graph.o: graph.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)util.o: util.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)gf.o: gf.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)extension.o: extension.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)gf_test.o: gf_test.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)extension_test.o: extension_test.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)fmatrix.o: fmatrix.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)ematrix.o: ematrix.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)fmatrix_test.o: fmatrix_test.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)polynomial.o: polynomial.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)util_test.o: util_test.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)solver.o: solver.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)scale.o: scale.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)solver_test.o: solver_test.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)ematrix_test.o: ematrix_test.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)gf_perf.o: gf_perf.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)extension_perf.o: extension_perf.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^

$(bits)geng_test.o: geng_test.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $^
