main.o: main.cc global.hh

graph.o: graph.cc graph.hh

util.o: util.cc util.hh

gf.o: gf.cc gf.hh

extension.o: extension.cc extension.hh

tests.o: tests.cc

gf_test.o: gf_test.cc gf_test.hh test.hh

extension_test.o: extension_test.cc extension_test.hh test.hh

fmatrix.o: fmatrix.cc fmatrix.hh

matrix_test.o: matrix_test.cc matrix_test.hh test.hh

ematrix.o: ematrix.cc ematrix.hh

fmatrix_test.o: fmatrix_test.cc fmatrix_test.hh

polynomial.o: polynomial.cc polynomial.hh
